### PR TITLE
dotenv, docker, security, & editorconfig

### PR DESCRIPTION
**Pull request by jeffturcotte**
Sorry that this pull request is too big.

Includes key dotenv and security stuff.

### CODE REVIEW

**Comment by khamer** [comment]
* There's an extra brace in composer.json (line 46) which makes the composer.json invalid.
* .editorconfig - do we really want 2 spaces for other .yml and .json files? I think we should just set it to four spaces for all filetypes.
* might want to add the craft license key file (craft/config/license.key) to the .gitignore(s)
* rather than hard coding the testToEmailAddress, if we're going to make everything else ENV variables let's make that one too

I am still finishing going through the process to get it up and running locally, downloading the imarcagency container is just taking a long time.

**Comment by khamer** [comment]
I'm not sure how docker-bootstrap.sh is supposed to be run - I would have expected it to run on docker-compose up, but it doesn't seem to. I see an error coming from itmundi/schematic complaining that CRAFT_FRAMEWORK_PATH isn't defined; I'm not sure if that's related.

**Comment by jeffturcotte** [comment]
I'm gonna fix the trivial issues above and then we can review the schematic issue.

**Comment by jeffturcotte** [comment]
- Extra brace fixed
- Re: .editorconfig. 2 spaces is more of the common standard for yml and json configs, which is why its different. composer is the outlier in that it does 4 spaces. NPM's package.json does 2 spaces by default.
- Added license.key to the gitignore
- Added test email to .env. I'm sure we'll continually be adding ENV vars for config stuff.

docker-bootstrap.sh is run in the container by the entrypoint script... you can see it being mounted in the docker-compose.yml. It means a "one-step" install, but I go back and forth as to where it should live and be run from. I just started everything without issue. I'm going to upgrade my composer packages and try again to see if I can replicate your issue.

**Comment by jeffturcotte** [comment]
Accidentally merged. Reset and reopened here: https://github.com/imarc/padstone/pull/4

**Comment by khamer** [comment]
I ran

```
$ composer install --ignore-platform-reqs
$ composer run create-project
$ docker-compose up
```

This looks really promising, but doesn't work. calling schematic throws this error, even when I go into the container and run schematic directly. I tried to look up solutions for this, but didn't find any skimming through results.

```
docker@682a14dd4487:/var/www$ /var/www/vendor/bin/schematic import
PHP Fatal error:  Uncaught Error: Class 'Craft\ErrorHandler' not found in /var/www/craft/app/framework/YiiBase.php:213
Stack trace:
#0 /var/www/craft/app/framework/base/CModule.php(393): YiiBase::createComponent(Array)
#1 /var/www/vendor/itmundi/schematic/src/Console/App.php(197): CModule->getComponent('errorHandler', true)
#2 /var/www/craft/app/framework/base/CApplication.php(468): NerdsAndCompany\Schematic\Console\App->getComponent('errorHandler')
#3 /var/www/craft/app/framework/base/CApplication.php(833): CApplication->getErrorHandler()
#4 /var/www/vendor/itmundi/schematic/src/Console/App.php(238): CApplication->handleError(8, 'Use of undefine...', '/var/www/craft/...', 458)
#5 /var/www/craft/app/Craft.php(458): NerdsAndCompany\Schematic\Console\App->handleError(8, 'Use of undefine...', '/var/www/craft/...', 458, Array)
#6 /var/www/craft/app/Craft.php(348): Craft\Craft::_importFile('/var/www/craft/...')
#7 /var/www/vendor/itmundi/schematic/src/Console/App.php(55): Craft\Craft::import('app.assetsource...')
#8 /var/www/craft/ in /var/www/craft/app/framework/YiiBase.php on line 213

Fatal error: Uncaught Error: Class 'Craft\ErrorHandler' not found in /var/www/craft/app/framework/YiiBase.php on line 213

Error: Class 'Craft\ErrorHandler' not found in /var/www/craft/app/framework/YiiBase.php on line 213

Call Stack:
    0.0002     374216   1. {main}() /var/www/vendor/itmundi/schematic/bin/schematic:0
    0.0068    1405608   2. YiiBase::createApplication() /var/www/vendor/itmundi/schematic/bin/schematic:77
    0.0082    1738976   3. CApplication->__construct() /var/www/craft/app/framework/YiiBase.php:121
    0.0095    1918296   4. NerdsAndCompany\Schematic\Console\App->init() /var/www/craft/app/framework/base/CApplication.php:170
    0.0095    1918304   5. Craft\Craft::import() /var/www/vendor/itmundi/schematic/src/Console/App.php:55
    0.0095    1919184   6. Craft\Craft::_importFile() /var/www/craft/app/Craft.php:348
    0.0095    1920096   7. NerdsAndCompany\Schematic\Console\App->handleError() /var/www/craft/app/Craft.php:458
    0.0095    1920096   8. CApplication->handleError() /var/www/vendor/itmundi/schematic/src/Console/App.php:238
    0.0100    1981568   9. CApplication->getErrorHandler() /var/www/craft/app/framework/base/CApplication.php:833
    0.0100    1981568  10. NerdsAndCompany\Schematic\Console\App->getComponent() /var/www/craft/app/framework/base/CApplication.php:468
    0.0100    1981568  11. CModule->getComponent() /var/www/vendor/itmundi/schematic/src/Console/App.php:197
    0.0100    1981944  12. YiiBase::createComponent() /var/www/craft/app/framework/base/CModule.php:393
```

**Pull request merged**
